repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest tests/ --cov=simplebayes --cov-fail-under=100 -q
        language: system
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 simplebayes tests
        language: system
        pass_filenames: false

      - id: pylint
        name: pylint
        entry: pylint simplebayes tests --exit-zero
        language: system
        pass_filenames: false
