language: python
cache:
  - apt
  - pip
sudo: false
python:
  - "2.7"
install:
  - pip install -r setup/requirements.dev.txt
  - wget https://pypi.python.org/packages/source/p/pylint/pylint-1.4.3.tar.gz
  - tar -xvf pylint-1.4.3.tar.gz
  - cd pylint-1.4.3
  - python setup.py install
  - cd ..
script:
  - nosetests tests/test.py --with-coverage --cover-package=simplebayes --cover-min-percentage 100
  - flake8 simplebayes tests
  - pylint simplebayes tests
